name:                 projeto-json
version:              0.1.0.0
visibility:           public
id:                   projeto-json-0.1.0.0-JLlLqRbzWUQCaUHZLfD1Kw
key:                  projeto-json-0.1.0.0-JLlLqRbzWUQCaUHZLfD1Kw
license:              BSD-3-Clause
maintainer:           seuemail@email.com
author:               Seu Nome
homepage:             https://github.com/seuusuario/projeto-json#readme
abi:                  9a2d22e8a7c6e1e56d29aad8f2bb2bf3
exposed:              True
exposed-modules:      SimpleJSON
hidden-modules:       Paths_projeto_json
import-dirs:
    C:\Users\thall\projetos\Haskell\projeto-json\.stack-work\install\40af69bc\lib\x86_64-windows-ghc-9.10.3-b42a\projeto-json-0.1.0.0-JLlLqRbzWUQCaUHZLfD1Kw

library-dirs:
    C:\Users\thall\projetos\Haskell\projeto-json\.stack-work\install\40af69bc\lib\x86_64-windows-ghc-9.10.3-b42a\projeto-json-0.1.0.0-JLlLqRbzWUQCaUHZLfD1Kw
    C:\Users\thall\AppData\Local\Programs\stack\x86_64-windows\msys2-20240727\mingw64\lib
    C:\Users\thall\AppData\Local\Programs\stack\x86_64-windows\msys2-20240727\mingw64\bin

library-dirs-static:
    C:\Users\thall\projetos\Haskell\projeto-json\.stack-work\install\40af69bc\lib\x86_64-windows-ghc-9.10.3-b42a\projeto-json-0.1.0.0-JLlLqRbzWUQCaUHZLfD1Kw
    C:\Users\thall\AppData\Local\Programs\stack\x86_64-windows\msys2-20240727\mingw64\lib
    C:\Users\thall\AppData\Local\Programs\stack\x86_64-windows\msys2-20240727\mingw64\bin

dynamic-library-dirs:
    C:\Users\thall\projetos\Haskell\projeto-json\.stack-work\install\40af69bc\lib\x86_64-windows-ghc-9.10.3-b42a
    C:\Users\thall\AppData\Local\Programs\stack\x86_64-windows\msys2-20240727\mingw64\lib
    C:\Users\thall\AppData\Local\Programs\stack\x86_64-windows\msys2-20240727\mingw64\bin

data-dir:
    C:\Users\thall\projetos\Haskell\projeto-json\.stack-work\install\40af69bc\share\x86_64-windows-ghc-9.10.3-b42a\projeto-json-0.1.0.0

hs-libraries:         HSprojeto-json-0.1.0.0-JLlLqRbzWUQCaUHZLfD1Kw
include-dirs:
    C:\Users\thall\AppData\Local\Programs\stack\x86_64-windows\msys2-20240727\mingw64\include

depends:              base-4.20.2.0-39f9
haddock-interfaces:
    C:\Users\thall\projetos\Haskell\projeto-json\.stack-work\install\40af69bc\doc\projeto-json-0.1.0.0\projeto-json.haddock

haddock-html:
    C:\Users\thall\projetos\Haskell\projeto-json\.stack-work\install\40af69bc\doc\projeto-json-0.1.0.0
